In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.arima.model import ARIMA
from sklearn.model_selection import GridSearchCV

In [2]:
# Code written by Joseph Nelson.

def interpret_dftest(dftest):
    dfoutput = pd.Series(dftest[0:2], index=['Test Statistic','p-value'])
    return dfoutput

In [5]:
df3 = pd.read_csv('data/sams_clean_data.csv')
df3.set

In [6]:
df3.head()

,yyyymmdd,lat,long,station_id,acton_id,station_name,elevation,wteq_amt,wteq_med,wteq_amt_pct_med,...,"LOWER COLUMBIA, HOOD RIVER",OWYHEE MALHEUR,"RAFT, GOOSE, SALMON FALLS, BRUNEAU",SNAKE ABOVE PALISADES,"UMATILLA, WALLA WALLA, WILLOW",UPPER CLARK FORK RIVER BASIN,"WEISER, PAYETTE, BOISE","WHITE, GREEN, CEDAR, SKYKOMISH, SNOQUALMI, BAKER, SKAGIT",WILLAMETTE,"YAKIMA, AHTANUM"
0,2011-02-10,48.566667,-115.450000,311,15A08S,Banfield Mountain,5600,12.1,12.2,99.0,...,0,0,0,0,0,0,0,0,0,0
1,2011-02-10,48.300000,-116.066667,323,16A08S,Bear Mountain,5400,37.4,38.6,97.0,...,0,0,0,0,0,0,0,0,0,0
2,2011-02-10,48.983333,-115.816667,918,15A05S,Garver Creek,4250,7.7,6.9,112.0,...,0,0,0,0,0,0,0,0,0,0
3,2011-02-10,48.916667,-114.766667,500,14A11S,Grave Creek,4300,13.1,11.4,115.0,...,0,0,0,0,0,0,0,0,0,0
4,2011-02-10,48.300000,-114.833333,510,14A14S,Hand Creek,5035,9.6,7.8,123.0,...,0,0,0,0,0,0,0,0,0,0